package com.racion.diariomercado.domain.repository

import com.racion.diariomercado.core.AppResult
import com.racion.diariomercado.domain.model.DailySummary
import com.racion.diariomercado.domain.model.DiaryEntry
import com.racion.diariomercado.domain.model.WeeklyReport
import kotlinx.coroutines.flow.Flow
import java.time.LocalDate

/**
 * The user's food diary: entries, plus the day/week aggregates the screens render.
 *
 * Contract:
 * - Reads are observable ([Flow]) because the diary is the one part of the app that is
 *   genuinely local-first: the flow must emit from the local cache immediately and then
 *   re-emit when the remote write lands, so the UI never waits on the network.
 * - Writes are `suspend` and return [AppResult]; a write that cannot reach the network must
 *   still be accepted locally (queued), not rejected.
 * - The implementation owns aggregation. Callers never fold over raw entries to build a
 *   summary — see [observeDay].
 */
interface DiaryRepository {

    /**
     * Emits the summary for [date], starting with whatever is cached and updating as it changes.
     *
     * The returned flow must never complete and never throw; a failure to read is surfaced as
     * an "empty day" emission, not as an exception on the collector.
     */
    fun observeDay(date: LocalDate): Flow<DailySummary>

    /** Same contract as [observeDay], for the seven days starting at [weekStart] (a Monday). */
    fun observeWeek(weekStart: LocalDate): Flow<WeeklyReport>

    /**
     * Appends [entry] to the diary and updates the day's running total in the same transaction.
     *
     * Returns [AppResult] of [Unit], not an id: [DiaryEntry.id] is generated by the **caller**
     * before the call, precisely so a write can be retried idempotently after an offline queue
     * drains. There is no server-assigned id to hand back, and a repository that minted one here
     * could not honour that guarantee.
     */
    suspend fun addEntry(entry: DiaryEntry): AppResult<Unit>

    /** Removes an entry and decrements the day's running total. Missing ids are a no-op success. */
    suspend fun deleteEntry(entryId: String): AppResult<Unit>

    /**
     * Most recently logged entries across all days, newest first. Used by the "Escanear" screen
     * to show the scan history strip.
     */
    suspend fun recentScans(limit: Int = 5): AppResult<List<DiaryEntry>>
}
